languages:
  Python: true
engines:
  fixme:
    enabled: true
    config:
      strings:
      - FIXME
      - BUG
      - CUSTOM
      - TODO
  duplication:
    enabled: true
    config:
      languages:
      - python
  radon:
    enabled: true
  pep8:
    enabled: true
ratings:
  paths:
  - "**.py"
exclude_paths:
- "*/migrations/*"
- "*test*"
