engines:
  duplication:
    enabled: true
    config:
      languages:
        python:
          mass_threshold: 26
          python_version: 3
  fixme:
    enabled: true
  radon:
    enabled: true
    config:
      threshold: "A"
ratings:
  paths:
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths:
- wizard_builder/migrations/0001_initial.py
