engines:
  duplication:
    enabled: true
    config:
      languages:
        python:
          mass_threshold: 20 # default is 32
          python_version: 3
  radon:
    enabled: true
    config:
      threshold: "A" # default is "B"
ratings:
  paths:
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths:
- wizard_builder/tests/
- wizard_builder/migrations/
