codecov:
  branch: master

coverage:
  precision: 1
  round: down
  range: "70...100"

  notify:
    slack:
      default:
        url: secret:K7dx0QkjO+IkK9abC6CIFJYrUKjcFYjr0Unubid2uZ0zykPfD0NptuiGGH9v3DRYlx1XTq5NrooEtz923k2F8virdTImOGrTFGuXHSFCmMVzv3VEhQGGv9L8mGknTXSOrI6/mjJ+xtlmj7PfVp6EbU7r8gWWHKAOwsMP+WetCt8=
        threshold: .5
        branches: null
        attachments: "sunburst, diff"
        only_pulls: true

comment:
  layout: "header, diff, changes, sunburst, uncovered"
  branches: null
  behavior: default
