language: python
python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"
sudo: false
env:
    - TOXENV=django18
    - TOXENV=django110
    - TOXENV=django111
    - TOXENV=djangodev
matrix:
    exclude:
        - python: "2.7"
          env: TOXENV=djangodev
        - python: "3.3"
          env: TOXENV=django110
        - python: "3.3"
          env: TOXENV=django111
        - python: "3.3"
          env: TOXENV=djangodev
        - python: "3.4"
          env: TOXENV=djangodev
        - python: "3.5"
          env: TOXENV=djangodev
    allow_failures:
        - python: "3.6"
          env: TOXENV=djangodev
install:
    - pip install -r requirements/test.txt
before_script:
    - isort --check-only --diff --quiet
script:
    - flake8 .
    - tox
after_success:
    - codecov -e TOXENV
notifications:
  slack:
    secure: LAJQUhlhacL5KKM0hXdTGQUtchhsrZgV1JyNUI+3GpM/UdLGvQSMpGU6ZaLp8DNYFNhhzaU2YllMgFU8qz13vVeViveVKiD+litmpCM4CFJk6shvoHyXsAXDrC0wUZY7ApY8cliA/8w1Em+CDYb1H+LMtkMm4YXLb08NcLspr1/pBr0N2b/L0pYTq41luERmGn6Rr5BCI3RFsLB9GN5vBzmTZ+6APirc/qt+gFJ4KXrzMqa0p1LDpNGXJJI4pjXnfdZwqJXcBp/DqY+nVczIXVppwmjhTVTmoDwyXsaOosu7G4b2kM1ZRmV560BqTLjV177Qe2+FfvcekAsV2GXl9PNGhhtdC9D0H3qpisZp7P1Ge134lCLeEu9qR2dD1qJs76xJRDWzyasOP9q/eedd0RYk55jwTRVwV4WpjD/MrusojRZo+ApWEIvHM4NIOHLGXLUqbn0C5ssJtMf2/tLCxs7FSWKp1bSv6JCMY3ekNuM0d7y85B3tjdl+KI4+/2KYJaNH8oMUfaMAd4vNMxlsVKO+LQmf/+J4ElJWTsHa5Plv0bIU1R6iAYUCMR6uzAHMiVFyJxqUwbGhc6y7r+rDxTuGrsWMjWUqZa9QnH4ogPinDkuLN2lbwfRbXSdtfJ1riJmvn1mfg/cgZWdA13M2o32Pj1CqNVeD3tqQ9ciHfLQ=
branches:
  only:
    - master
