language: python
python:
  - "3.6"
sudo: false
cache: pip
env:
  global:
    - DJANGO_111=Django>=1.11,<2.0
    - DJANGO_DEV=https://github.com/django/django/tarball/master
  matrix:
    - DJANGO_VERSION=$DJANGO_111
    - DJANGO_VERSION=$DJANGO_DEV
matrix:
  fast_finish: true
  allow_failures:
    - env: DJANGO_VERSION=$DJANGO_DEV
install:
  - pip install -r callisto_core/requirements/test.txt --upgrade
  - pip install $DJANGO_VERSION
script:
  - make test
notifications:
  slack:
    secure: hMHHY0B/DUPsXnrHkgtbV526fqq2E8ZBYf6jODe6JbFrBKHy/8bFsSf2ET6w3He1VNiUJB1i4WLB4YQarjIWLMzd0zD7nXbtkm4tSYWX3fFd9GZ/HNn9U+c7Ks4Z6KKQ5nyIpBxSxNoJ7cT+AOq/p4uBwHZtvsGsOkEbLzkqdkdkvZl7tKWJ9F47yHu+Kn+uhjmsQa6ZIz8Xjy3Tof12fmnVUaCamtKwM5Tq4s/6p8RNNHpPYUUUUojjMH/2A47s3n3Kc1IkV+EAo+MAIO/dZec39NqFe9Pmm02AWdhEZF9tPHjBhApdAuSalgep1RjckfRSQs7uSc+Tsq0E0/qsfOcZG2WjFdS3ajfE20qyeKH1nYKTs8EAt0LXeGJ2ZvIVTujrKDRy7YgEfPgewkuNkopoj8KVkXUqOd5t4esGFB+Xr2EXUGRCx/XJLlcsNJNUQxBeQcZVxeL9xwwFofKFSYhIcvwfdHgPqfkY6vqvxyTLDsEndZHmxTu7OiZZWr384b9l1Beot0xipmUMVqUnDwS6PTiIbhc/e616NzLpSvLSXYBlnpvDDK+voqZuul1YsFUTMRkj7cmnWdj2COusj1RurlmBJnZjpEWEnWBVpGDmaKu5i8hqi7/ai41eGEiJfC6T4QUKVSMCP5eQ0H7HA+AbIKO1oMvFjq4VxnXd+0I=
  email: false
